version: '3.3'

services:
   db:
     build: ./database
     # volumes:
     #   - db_data:/var/lib/mysql
     restart: always
     ports:
       - "5635:3306"

   wordpress:
     depends_on:
       - db
     image: wordpress
     ports:
       - "80:80"
     volumes:
       - "./:/var/www/:cached"
       - "./public:/var/www/html:cached"
       - "./phpOverrides.ini:/usr/local/etc/php/conf.d/uploads.ini:cached"
     environment:
       VIRTUAL_HOST: "localhost"
       DB_HOST: "db"
       DB_NAME: "wordpress"
       DB_USER: "wordpress"
       DB_PASSWORD: "wordpress"
       APPLICATION_ENV: "dev"
       WP_HOME: "http://localhost"
       WP_SITEURL: "http://localhost"
       WP_DEBUG: "false"
